[[bench]]
name = "blockjack"
harness = false

[dependencies]
rand_chacha = "0.9.0"
rayon = { version = "1.10.0" }
tfhe = { version = "1.2.0", features = ["integer"] }

[dev-dependencies]
criterion = "0.6.0"

[lib]

[package]
edition = "2021"
name = "blockjack"
version = "0.1.0"
